"use client";
import Link from "next/link";
import {useEffect,useState} from "react";

type P={id:string;name:string;description:string;category:string;premium:boolean;price:number;views:number;downloads:number;coverUrl?:string|null;owner:{id:string;name:string|null;role:string}};

export default function Home(){
 const [ps,setPs]=useState<P[]>([]);const [q,setQ]=useState("");const [cat,setCat]=useState("");const [premium,setPremium]=useState("");const [sort,setSort]=useState("new");const [error,setError]=useState("");
 async function load(){try{setError("");const r=await fetch(`/api/projects?q=${encodeURIComponent(q)}&category=${encodeURIComponent(cat)}&premium=${premium}&sort=${sort}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!Array.isArray(d))throw new Error(d.error||"Gagal memuat project.");setPs(d)}catch(e){setPs([]);setError(e instanceof Error?e.message:"Gagal memuat project.")}}
 useEffect(()=>{load()},[cat,premium,sort]);
 return <><section className="hero"><span className="pill">DEVELOPER MARKETPLACE</span><h1>Discover projects worth shipping.</h1><p className="muted">Free and premium projects, creator profiles, ratings, downloads, wishlist, and Premium membership via Admin.</p></section><div className="search"><input placeholder="Search projects, tags, descriptions…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">All categories</option>{["Web","Mobile","AI","SaaS","Backend","UI/UX","Other"].map(x=><option key={x}>{x}</option>)}</select><select value={premium} onChange={e=>setPremium(e.target.value)}><option value="">All pricing</option><option value="false">Free</option><option value="true">Premium</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Newest</option><option value="old">Oldest</option><option value="popular">Most downloaded</option><option value="views">Most viewed</option><option value="price_asc">Cheapest</option><option value="price_desc">Most expensive</option></select><button onClick={load}>Search</button></div>{error&&<div className="panel danger">{error}</div>}<div className="grid">{ps.map(p=><Link className="card" href={`/projects/${p.id}`} key={p.id}><div className="cover">{p.coverUrl?<img src={p.coverUrl} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:"PROJECT"}</div><div className="cardbody"><div><span className="pill">{p.category}</span><span className="pill">{p.premium?"PREMIUM":"FREE"}</span></div><h3>{p.name}</h3><p className="muted">{p.description.slice(0,110)}</p><div className="row"><small>{p.owner.name||"Creator"}</small><small>{p.views} views · {p.downloads} downloads</small></div></div></Link>)}</div>{!error&&!ps.length&&<div className="panel">No projects match the current filters.</div>}</>
}
